### ISSUE TITLE
Match %

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#100]
Make the command minimum match % 60 or so

**Comment by codeman1o1** [comment]
I am missing some context.
Also please use an issue template

**Comment by JustIanJ** [comment]
Je weet heus wat ik bedoel, nu niet don doen.

**Comment by JustIanJ** [comment]
Dom*

**Comment by codeman1o1** [comment]
I know that you know that I know what you mean, but for other users some context would be nice

**Comment by JustIanJ** [comment]
Do it yourself then, nobody reads this

**Comment by codeman1o1** [comment]
What @JustIanJ means is that if an invalid command is being sent, currently it TIJK Bot will try to search for a suggestion. But what @JustIanJ suggests is that it must match at least 60%
