### ISSUE TITLE
One word story admin

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#107]
### Describe the bug

Disclaimer: this isnt really a bug, nor a feature request, it's something in between.

When an admin or owner types his 1 word they can still type after they got the role last word, this is because admin is a higher role than last word, this should stay the same, but can you make it so that if the owner or admin types a second message and he has the last word role that the second msg gets deleted? Same for 3rd and 4th and so on ofc

### To reproduce

Type a word in #one-word-story as an admin or owner
Type another word
See "problem"

### Expected behavior

When an admin or owner types more than 1 message and the admin or owner has the last word tole all the new msgs keep getting deleted

### Screenshots

![Screenshot_20220305-032244_Discord](https://user-images.githubusercontent.com/90295730/156864161-5f192191-4cec-48e8-91dc-18dbb885fe5b.png)

**Comment by codeman1o1** [comment]
Fixed

**Comment by JustIanJ** [comment]
Tysm
