### ISSUE TITLE
TIJK Bot reads the messages from first sent to last sent. It doesn't look for the rule number. There is probably an unnumbered message inside the channel

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#109]
You said this about 3mo ago, but can you make it so it does work that way?

**Comment by JustIanJ** [comment]
Issue #43 to be clear

**Comment by JustIanJ** [comment]
So can you make it so it does look for the number?

**Comment by codeman1o1** [comment]
Unfortunately I this will be hard because of text formatting, but if every message is numbered, there should be no problem in `.readtherules`

**Comment by JustIanJ** [comment]
Yes true but 3mo ago there was a problem you saw that and maybe you couldve fixed it this way
