### ISSUE TITLE
Ar en rr

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#11]
![Screenshot_20211106-142952_Discord.png](https://user-images.githubusercontent.com/90295730/140611483-ea5880f0-98e2-4b11-9d8b-e3f2d405d669.png)
Zou je misschien de nickname naar originele dc name kunnen maken met #code, dus codeman1o1#6969 by codeman1o1#6969 (weet jouw code niet)

**Comment by JustIanJ** [comment]
En mss Role "clash royale ping" dus met die 2 trema's?

**Comment by JustIanJ** [comment]
Doe dit dan ook bij .ar

**Comment by codeman1o1** [comment]
Wil je dit bij iedere naam en command?

**Comment by codeman1o1** [comment]
De trema's zal ik aan werken

**Comment by JustIanJ** [comment]
> 
> 
> Wil je dit bij iedere naam en command?

liever wel

**Comment by codeman1o1** [comment]
Ik denk dat het dan een beetje chaotisch wordt. Ik denk dat het dan verstandig is om dan alleen de admins te doen of helemaal niet. Wat denk jij?

**Comment by JustIanJ** [comment]
Alleen admins

**Comment by codeman1o1** [comment]
Oké, dan ga ik dat regelen!
