### ISSUE TITLE
.hack command

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#13]
Ja gwn een .hack command en dan een gek matrix gifje.
Bijv.
.hack @codeman1o1

**Comment by codeman1o1** [comment]
Welke "stages" van de hack wil je?
Een stage is bijv.
_Hacking user...
Getting information..._

**Comment by JustIanJ** [comment]
Psssst kijk alles maar bij dank memer af

**Comment by codeman1o1** [comment]
Ok, maar ik ga wel een paar dingen veranderen zodat de docent het niet verdacht vind

**Comment by JustIanJ** [comment]
Welke docent?

**Comment by codeman1o1** [comment]
Hij/zij/het begreep de grap niet...

**Comment by codeman1o1** [comment]
> Psssst kijk alles maar bij dank memer af

Wil je dat ik alles exact kopiëer?

**Comment by JustIanJ** [comment]
de stages:
Getting Ip-addres en dan met de bot wat random ip's generaten
Buying data from the dark web
installing trojan on pc
getting into OS
changing BIOS Settup
installing 24 virusprograms on pc
Slowly taking RAM
Showing personal data to scare you
deleting windows
deletion complete, windows was removed
making pc useless
done
the pc of the selected user has been totally legitimately hacked.
