### ISSUE TITLE
een .birthday command

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#15]
deze command laat een bericht zien waarin onze verjaardagen staan.

**Comment by codeman1o1** [comment]
Zou je mij de verjaardagen doorsturen in Discord codeman1o1#1450

**Comment by JustIanJ** [comment]
Oke ik stuur degenen die ik weet, misschien ook een idee om op de verjaardag een privébericht te laten sturen door de bot?

**Comment by codeman1o1** [comment]
Ik laat de bot niet de persoon feliciteren
