### ISSUE TITLE
bring back the help menu

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#156]
### Describe your fix/feature

When TIJK-Bot started we had the .help command which showed all commands sorted in categories, can you please bring back such a thing? /help?
I really used this quite a bit. And i would like it back.

### Is your feature request related to a problem?

Yes, idk how every command is called.

### Additional context

Nvt

**Comment by codeman1o1** [comment]
All commands are already listed in the slash commands menu. Slash commands are also auto completed

**Comment by codeman1o1** [comment]
I am going to close this issue
