### ISSUE TITLE
github in tijk

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#158]
### Describe your fix/feature

Can you make it so that this type of messages:
![Screenshot_20220419-000743_Discord](https://user-images.githubusercontent.com/90295730/163885319-321d54ad-7e38-41e7-a4dd-9e37fe62699e.png)
Are sent by tijkbot instead of this github bot?

### Is your feature request related to a problem?

Not directly

### Additional context

Nvt

**Comment by codeman1o1** [comment]
I will not do this.
Also, that is not a bot. It is a webhook
