### ISSUE TITLE
waar is deze code voor?

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#16]
if "youtube.com/watch?v=dQw4w9WgXcQ" in message.content.lower():
        await message.delete()
        embed = discord.Embed(color=0x0DD91A)
        embed.add_field(
            name=f"Rick Roll alert!",
            value=f"This message wil delete itself after 5 seconds",
            inline=True,
        )

**Comment by codeman1o1** [comment]
Anti RickRoll

**Comment by JustIanJ** [comment]
Close em maar
