### ISSUE TITLE
`/database querylist` slash command

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#174]
### Describe your fix/feature

When i use /database  i do not know every query, can you please make it so we get a list of all existing querrys so i can choose which one i want

### Is your feature request related to a problem?

Yes it's hard to use /database since i do not know every querry by heart

**Comment by JustIanJ** [comment]
Just to be clear, make this for all /database cmds, so also /database set and /database get

**Comment by codeman1o1** [comment]
I will not make this because it will take too long to go through all database entries and get the name of the entry. Instead, I can make a slash command `/database querylist`. Do you want this?

**Comment by JustIanJ** [comment]
Yes, please
