### ISSUE TITLE
[SUGGESTION] More API's

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#179]
### Describe your fix/feature

Can you find more fun api's for the api cmd? it's starting to get a bit boring.

### Is your suggestion related to a problem?

yes i'm getting bored of the current api's i've seen almost everything already

### Additional context

n/a

**Comment by codeman1o1** [comment]
I already did, but I found no actual fun API's. Could you maybe search?

**Comment by JustIanJ** [comment]
i will look for them when i have time

**Comment by codeman1o1** [comment]
Okay, please create a new issue then. I am going to close this now
