### ISSUE TITLE
Moderator only stuffy

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#2]
Kun je aub logs in #moderator-only plaatsen (dus kicks, bans, mutes enz.) Mss een command die een kanaal een log kanaal maakt? Die alleen voor admin/owner werkt.

**Comment by codeman1o1** [comment]
Wil je het in #moderator-only of een nieuw kanaal (bijv. #tijkbot-logs)?

**Comment by JustIanJ** [comment]
Een command die dat kanaal als log kanaal zet, is dat mogelijk?

**Comment by codeman1o1** [comment]
Omdat TIJK Bot maar op 1 server draait, is die command overbodig.
Als je een kanaal maakt, kan ik er voor zorgen dat het in dat kanaal wordt gepost

**Comment by JustIanJ** [comment]
Doe maar in moderator only

**Comment by codeman1o1** [comment]
Oké

**Comment by codeman1o1** [comment]
Damn it, waarom sluit ik telkens de issues als ze nog niet af zijn

**Comment by JustIanJ** [comment]
Doe je zelf 😉

**Comment by codeman1o1** [comment]
Gedaan! (Andere dingen zijn ook veranderd)
