### ISSUE TITLE
[SUGGESTION] better pingpoll

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#220]
### Describe your fix/feature

add a slash-command which allows you to answer a pingpoll with an exact time.
E.g. "18:53" or "in 10 minutes" this will be displayed in the column "in a moment" (which already exists) together with your discord username.
for example:
someone pingpolls
i use: "/pingpoll in 10 minutes" or "/pingpoll time 20:31"
and TIJK-Bot then shows the time (to) when you are available in the column "in a moment" together with your discord username.

### Is your suggestion related to a problem?

yes, the "in a moment" answer is to imprecise. 

### Additional context

NVT

**Comment by JustIanJ** [comment]
@codeman1o1

**Comment by JustIanJ** [comment]
when are you able to work on it?

**Comment by codeman1o1** [comment]
Do you see me as an assignee on this issue?
Exactly.

**Comment by JustIanJ** [comment]
> Do you see me as an assignee on this issue? Exactly.

when you become an assignee does that mean you're working on it?

**Comment by codeman1o1** [comment]
Or it is on my todo

**Comment by JustIanJ** [comment]
okay, thank you i did not know this

**Comment by JustIanJ** [comment]
Maybe you could make it without a slash command? it would be like:
1. press the "in a moment" button
2. get a ephemeral message in which you can select a time
3. get the choice between e.g.: 15:29 or "in 10 minutes"
3. get it set in the table (and ofc if they choose the second one, change it every minute so it is and stays correctly)
(maybe exceed the maximum time for a PingPoll if the "in a moment" is too long?)

**Comment by codeman1o1** [comment]
I am going to do it as following:

The first change:
When someone pings, the Ping Poll will appear, but now with a dropdown. The dropdown allows the user who pinged to set a custom time (between 5 and 30 minutes, choices are per 5 minutes).
After the user selected an option, the dropdown will disappear.

The second change:
When a user clicks on the "In a moment" button, TIJK Bot will reply with an ephemeral message letting the user choose a time (between 5, and a number using the following formula: `time_left_for_pingpoll // 5 * 5`)
When the user selects an option, TIJK Bot will put the user in the "In a moment" field with an epoch timestamp (relative) for that time.
