### ISSUE TITLE
Bot opstarten

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#23]
Zou je de bot een bericht willen laten sturen in #moderator-only wanneer deze opgestart is (ook misschien voor de bèta-bot die op jouw pc staat een idee? En voor de Nieuwe Muziekbot?) dus bijv de msg "TIJK-Bot is opgestart" of bij de bèta-bot "De Bèta-TIJK-Bot is opgestart" of bij de muziekbot "de muziekbot is opgestart"
Mogelijk kan dit ook bij het afsluiten? het liefst eigenlijk allebei, zodat moderators de status van de bot(s) altijd bij kunnen houden.

**Comment by codeman1o1** [comment]
Dat is helaas niet mogelijk
