### ISSUE TITLE
Buttonrole ban

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#238]
### Describe your fix/feature

I would like to be able to ban someone from getting (some) buttonroles, so i suggest making a br ban cmd:
`/buttonroles ban <user> [role]`. To ban 1 specific role.
Role will not be manditory, so if you do not fill in a role, the user cannot use buttonroles anymore, if the user has some roles, they will keep them.
The message that shows when the user tries and fails to give the role is "You have been banned from giving yourself the (role) role, if you think this is a mistake, please contact the admins via a ticket." Or if they are completely banned: "You have been banned from using buttonroles, if you think this is a mistake, please contact the admins via a ticket."

This will be server specific and there also should be a `/buttonrole ban remove` command, which then shows a list of the banned  users/roles, only admins can use this command

### Is your suggestion related to a problem?

Yes, we have some people who should not be able to get some roles, but we want the rest of our users to still be able to get them.

**Comment by JustIanJ** [comment]
Also make it so that bans won't overlap
Like:
User banned from hypixel ping
User completely banned

This causes confusion so make it so that
If you ban someone completely, their role specific bans get removed and they will get an all role ban, and if they are completely banned, and you role ban them, you cannot do that

**Comment by codeman1o1** [comment]
It's quite difficult to implement a global button role ban, so I won't do that.

**Comment by codeman1o1** [comment]
Yes.
