### ISSUE TITLE
Messages counter

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#24]
Een idee om een counter te maken van hoeveel berichten iedere member stuurt? En dat dan door .msg op te kunnen vragen.

**Comment by codeman1o1** [comment]
> hoeveel berichten iedere member stuurt

Je bedoelt _ooit_ right?

**Comment by codeman1o1** [comment]
Waarvoor wil je dit gebruiken?

**Comment by JustIanJ** [comment]
> > hoeveel berichten iedere member stuurt
> 
> Je bedoelt _ooit_ right?

Ja

**Comment by JustIanJ** [comment]
> Waarvoor wil je dit gebruiken?

Leuke stats

**Comment by codeman1o1** [comment]
Wil je dat iedereen deze command mag gebruiken of alleen admins?

**Comment by JustIanJ** [comment]
Iedereen, is leuk
