### ISSUE TITLE
TIJK-Bot shutdown protection

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#241]
### Describe the bug

It is not 100% a bug, but this was the best fit. I notice sometimes when for example a pingpoll gets used and the botowner starts to work on the bot/the bot restarts, it breaks the (in this case) pingpoll, so I have to deal with confused users.

### To reproduce

Use Pingpoll (or any button/time based command)
Shut down bot
See

### Expected behavior

i would have liked TIJK-Bot to delete/suspend those interactions, so users do not encounter them as often.

### Screenshots

Not quite handy, it is a pingpoll which fails with error: interaction failed because TIJK-Bot is offline.

### Additional context

If you need more info, just ask me in this thread

**Comment by codeman1o1** [comment]
This is a very small problem, and won't occur often so I won't fix it.
An alternative fix is to just manually delete the message.

**Comment by JustIanJ** [comment]
But that would still be manual
