### ISSUE TITLE
[BUG] Database mistake

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#247]
### Describe the bug

when you use /info user timmie644 it says that tim has 200000 warns, which cannot be right.

### To reproduce

use /info user timmie644
see error

### Expected behavior

show the real value

### Screenshots

![Screenshot_20220829_090219](https://user-images.githubusercontent.com/90295730/187143723-40388d64-d304-4dd8-9f63-343f9ff22463.png)

**Comment by codeman1o1** [comment]
This is correct. You can set the warns manually back by using `/database set <user> warns <the new amount of warns>`
