### ISSUE TITLE
de .warn command

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#26]
als deze command wordt uitgevoerd zou het er als volgt uit zien: ".warn @user (reason)" dan verschijnt er een bericht door TIJK-Bot: "How many warns would you like to give?" hieronder staan 3 buttons (net zoals bij pls search van Dank Memer), hierop staat een 1, een 2 en een 3, waarop de persoon klikt (een admin of ownerrank) bepaald hoeveel warns de persoon krijgt. dan veranderd het bericht van TIJK-Bot naar bijv. "gave @user (aantal warns) warns.". Iedere User heeft eerst 10 warns raken deze op? dan krijgt hij/zij 10 minuten mute, de warns worden gereset naar 10, raken ze weer op? 15 minuten mute, enzovoorts, dus iedere 10 warns (aantal vorige warn minuten)+5 minuten. (misschien moet er iets in de code gedaan worden i.v.m. 1 warn over hebben en dan 3 warns eraf willen halen???? dat je dan i.p.v. 10 warns maar 8 warns terug krijgt na de reset?) En een command ".warnadd @user (hoeveelheid warns)".

**Comment by codeman1o1** [comment]
Ik ga niet de tijd verhogen voor elke mute, dat is onnodig
