### ISSUE TITLE
/hamsteren.

### ISSUE THREAD

**Issue by codeman1o1** [codeman1o1/TIJK-Bot#264]
### Describe your fix/feature

/hamsteren.

### Is your suggestion related to a problem?

Albert Heijn

### Additional context

Hamsteren.

**Comment by JustIanJ** [comment]
LGTM

**Comment by JustIanJ** [comment]
https://www.youtube.com/watch?v=0fn4X2TLxNc
this is the one right?

**Comment by codeman1o1** [comment]
It was fun while it lasted. Closing it now.
