### ISSUE TITLE
hamstercounter

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#272]
### Describe your fix/feature

Make a command /hamstercounter  which shows how many times you have hamstered and how many times there has been hamstered in total. All in one message from tb

### Is your suggestion related to a problem?

No

### Additional context

React to this thread if you need any additional information

**Comment by codeman1o1** [comment]
See: https://github.com/codeman1o1/TIJK-Bot/issues/264#issuecomment-1324004644
