### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#3]
Ik ben momenteel natuurlijk owner van onze server en ik zie ook regelmatig 's nachts dat de bot offline is, zou ik op replit toegang mogen hebben om de bot te starten?

**Comment by codeman1o1** [comment]
Zou je me een screenshot willen sturen met bewijs?
Ik heb nodig
- De tijd
- De status van TIJK Bot
Stuur het A.U.B. naar codeman1o1#1450.
Zorg wel dat je het 's nachts stuurt

**Comment by JustIanJ** [comment]
Is dat per sé nodig? Ik ben sinds ongeveer 3 dagen geleden begonnen om echt optijd te gaan slapen, want soms had ik slaaptekort. Sws lijkt het me verstandig om op momenten dat jij er niet bent iemand te hebben die kan opstarten.

**Comment by codeman1o1** [comment]
Liever wel

**Comment by JustIanJ** [comment]
Dat ga ik niet doen. En de laatste zin van vorig bericht?

**Comment by codeman1o1** [comment]
Dit ga ik niet doen omdat je dan ook toegang hebt tot de Bot Token. Die wil ik ABSOLUUT geheim houden. Sorry

**Comment by JustIanJ** [comment]
Waarom niet!? Mag ik de bot niet opstarten?

**Comment by codeman1o1** [comment]
Omdat je geen toegang mag hebben tot de Bot Token
