### ISSUE TITLE
REACTIONSROLEZS

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#37]
**Is your feature request related to a problem? Please describe.**
Reactionroles for all roles

**Describe the solution you'd like**
An command for owners or admins to make reactionroles with custom messages and emojis

**Additional context**
Like mee6

**Comment by codeman1o1** [comment]
What should be the command? .rr (removerole) is already in use.

**Comment by JustIanJ** [comment]
.rero
