### ISSUE TITLE
Join and leave msgs

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#38]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make join and leaves msgs in the bot like shown in the pictures

**Additional context**

**Comment by JustIanJ** [comment]
![20211211_184534.jpg](https://user-images.githubusercontent.com/90295730/145686465-635151b8-1cfc-47e6-934f-7265ccfb7a46.jpg)
![20211211_184410.jpg](https://user-images.githubusercontent.com/90295730/145686468-241ffa94-dd1c-4f9f-b98c-4c216e581b2d.jpg)

**Comment by JustIanJ** [comment]
Also dm them like this
![20211211_185035.jpg](https://user-images.githubusercontent.com/90295730/145686592-da6a6a49-8d37-475f-8a8f-6b6c4d54e388.jpg)

**Comment by codeman1o1** [comment]
Is it okay if I change the text a little bit?

**Comment by JustIanJ** [comment]
Ofc
