### ISSUE TITLE
Help Msg

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#4]
ik citeer: 
If you need help with any of our bots please type
- !help for MEE6
- pls help for Dank Memer
- s!help for Statisfy
- m.help for TIJK Music (TIJK Bot module)
het gaat mij om de laatste, naar mijn weten is de TIJK Music bot tijdelijk niet beschikbaar, zou je dit weg kunnen halen als dat zo is?

**Comment by codeman1o1** [comment]
TIJK Music wordt een andere bot. Hier ga ik binnen kort aan werken.
