### ISSUE TITLE
[Mute doesn't mute]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#41]
**Describe the bug**
When the 10 warns are gone theres a message the member is going to be muted, but they are not. I had to do it manually.

**To Reproduce**
1. Warns are gone (0 left)
2. See error

**Screenshots**
I have no, but you can test it yourself

**Additional context**
-

**Comment by codeman1o1** [comment]
Do you mean this?
![Screenshot_2021-12-13-14-38-58-64_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/70335544/145822662-e34cdf2e-fa34-416f-bb92-00e8abd74011.jpg)

**Comment by JustIanJ** [comment]
No, when i warn a member and then when it should mute it doesnt

**Comment by codeman1o1** [comment]
Does the member have the `Muted` role?
And does `.mute` work?

**Comment by JustIanJ** [comment]
They do not have the role and idk if .mute works

**Comment by codeman1o1** [comment]
Can you try it?

**Comment by JustIanJ** [comment]
I get an error

**Comment by JustIanJ** [comment]
![Screenshot_20211213-144930_Discord.png](https://user-images.githubusercontent.com/90295730/145824141-8f277ae2-ea92-43e7-9f67-704fd323911d.png)

**Comment by codeman1o1** [comment]
TIJK Bot has insufficient permissions to assign that role to someone. Is the `Muted` role under the `TIJK Bot` role?

**Comment by JustIanJ** [comment]
That's the problem thanks
