### ISSUE TITLE
[.rtr]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#43]
**Describe the bug**
Wanneer ik .rtr 15 doe geeft hij het bericht voor regel 14.

**To Reproduce**
1. Use command ".rtr 15 @member"
2. See error

**Screenshots**
![Screenshot_20211214-220856_Discord.png](https://user-images.githubusercontent.com/90295730/146079679-acd714fc-a390-41d5-8d33-802063bdd665.png)

**Additional context**
Er is nu ook een 16e regel, althans die was er al, maar staat nu appart, kun je ook zorgen dat deze goed werkt met rtr?

**Comment by JustIanJ** [comment]
That should be fixed already

**Comment by codeman1o1** [comment]
Is this fixed?

**Comment by codeman1o1** [comment]
I am assuming it is fixed
