### ISSUE TITLE
[.help]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#45]
**Describe the idea you'd like**
Maak soortgelijke commands als onderstaand een ding.

**Additional context**

![Screenshot_20211214-221546_Discord.png](https://user-images.githubusercontent.com/90295730/146080639-b6a18cdf-d5c1-43ed-bbe7-5b960ed971fc.png)

**Comment by codeman1o1** [comment]
This is already implemented

**Comment by JustIanJ** [comment]
Okay thank you
