### ISSUE TITLE
API help

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#5]
in de api help msg staat:
I do not own the API's so I can't help you with something if it is a problem with the API!!
mogelijk vervangen door:
I do not own any of the API's, so if there occurs an issue, i cannot help you with it.
Klinkt wat beter in mijn oren.

**Comment by codeman1o1** [comment]
Dat klinkt inderdaad beter!

**Comment by codeman1o1** [comment]
Sorry, ik heb het per ongeluk gesloten

**Comment by JustIanJ** [comment]
Moet hier done label niet op?
