### ISSUE TITLE
[Een command]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#50]
**your feature request**
A clear and concise description of what the feature is. So i was thinking you have github and you have therrassium on it right? Maybe you can make 1 or 2 commands to plug your other project in the bot e.g. .mod/.therrassium to get the curseforge link and .modgithub/.therrassiumgithub to get the github link?

**Additional context**
None

**Comment by codeman1o1** [comment]
TIJK Bot is not in any way related to the Therrassium mod or other mods I am planning to make. I won't do this
