### ISSUE TITLE
[Help menu]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#51]
**Is your feature request related to a problem? Please describe.**
There is a problem with the help message. If you use .help you get this:
![Screenshot_20220102-052529_Discord.png](https://user-images.githubusercontent.com/90295730/147866215-ff092928-56db-415e-b8b8-d86d44a7ada8.png)
That is correct, but if you want to use .help Fun for example it does not work: ![Screenshot_20220102-052550_Discord.png](https://user-images.githubusercontent.com/90295730/147866225-65316d49-214e-41bf-9639-f307b9046f49.png)
And yes I do know this is because of case sensitivity and i was wondering if you could turn case sensitivity off? It is going to be very confusing for someone who doesn't know the bot.

**Describe the solution you'd like**
As i said turn off case sensitivity.

**Additional context**
None

**Comment by codeman1o1** [comment]
Please do not repeat questions.
Unfortunately not. The help command is provided by a Python package that I do not own.

**Comment by JustIanJ** [comment]
i'm sorry for repeating, i forgot.
