### ISSUE TITLE
[Help menu #2]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#52]
**Is your feature request related to a problem? Please describe.**
No, it's just something that might improve the bot.

**The problem**

If you use .help you get this:
![Screenshot_20220102-052529_Discord.png](https://user-images.githubusercontent.com/90295730/147866296-8cb59d9a-943b-4f35-8809-a24e03853c4e.png)
That is how it is and that is how it should be, but there is just one little thing i would like to propose. If you look closely you can see that there are numbers in front of every category e.g. fun is 5. Maybe you can add commands like: .help 5?
![Screenshot_20220102-052601_Discord.png](https://user-images.githubusercontent.com/90295730/147866351-dd019e52-ce57-40ce-942b-babc10f85d22.png)
It's a short way of saying .help Fun.
And it might just help to make the bot a little bit better and clearer

**Additional context**
None

**Comment by codeman1o1** [comment]
Unfortunately not. The help command is provided by a Python package that I do not own.
