### ISSUE TITLE
[SUGGESTION]allmee6commands

### ISSUE THREAD

**Issue by Gamer086** [codeman1o1/TIJK-Bot#67]
**Is your feature request related to a problem? If so, please describe. If not, skip this part**

**Describe your fix/feature**

**Additional context**

**Comment by codeman1o1** [comment]
Please fill in the fields. You can do this by editing your message

**Comment by Gamer086** [comment]
All the mee6 commands

**Comment by codeman1o1** [comment]
Please specify all commands and I will try to implement them

**Comment by Gamer086** [comment]
I dont know all the mee6 com so that sh1t bot can be banned from the tijk server

**Comment by codeman1o1** [comment]
If you don't know them, I can't implement them. Maybe ask the server owner for the features

**Comment by codeman1o1** [comment]
If the features won't be given soon, I will close this issue
