### ISSUE TITLE
help msg #2

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#7]
![image](https://user-images.githubusercontent.com/90295730/140494838-5fda3dad-a97a-482d-b1b3-e4307a68f066.png)
kun je de .website in de help message mss in de 2e rij zetten want anders klopt het niet.

**Comment by codeman1o1** [comment]
De .help command staat op alfabetische volgorde, dus dit laat ik zo

**Comment by JustIanJ** [comment]
Het ziet er niet netjes uit!
