### ISSUE TITLE
[.clean]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#82]
**Is your feature request related to a problem? If so, please describe. If not, skip this part**
Yes, the .clean command deletes bot msgs, but nog the msgs that are used to trigger the bot:
![Screenshot_20220117-112307_Discord.png](https://user-images.githubusercontent.com/90295730/149752261-54aba24d-6762-4f82-acd8-006780d654b5.png)

**Describe your fix/feature**
Also delete msgs where the prefixes are used e.g. !help !mute, pls dep or ,p and such things, everything like that, except this: `.mute` because this is used in for example rules and such sort.

**Comment by JustIanJ** [comment]
Github changed the this:
It should be between ` such thingys

**Comment by codeman1o1** [comment]
For this, I will have to know the prefix of every bot in the guild. For my knowledge is this not possible. What I can do is to make a list with the most popular bot prefixes.

**Comment by JustIanJ** [comment]
,  . pls ! S!

**Comment by codeman1o1** [comment]
Reopening because there is an issue

**Comment by JustIanJ** [comment]
Ok
