### ISSUE TITLE
[COMMANDS]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#83]
**Describe the reasoning**
I saw that gamer086 tried to make all mee6 commands in tijkbot, but he didnt finish his job. So I am here to do it
**The commands and how it should work**
![Screenshot_20220117-113213_Discord.png](https://user-images.githubusercontent.com/90295730/149753657-91ccb03a-5188-4555-8d55-38c40494933b.png)
**Additional context**
None

**Comment by codeman1o1** [comment]
Do these commands need to be admin-only commands?

**Comment by JustIanJ** [comment]
Yes please
