### ISSUE TITLE
[Warns]

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/TIJK-Bot#89]
Op hoelang staat de to tijd van 10 warns? 
Ps: wacht na je antwoord pls ff met sluiten.

**Comment by codeman1o1** [comment]
The timeout for a warn is 10 minutes (600 seconds) as stated here:
https://github.com/codeman1o1/TIJK-Bot/blob/d9c10a36ca030f42db360bf5ffa73237791cd568/cogs/event_handler.py#L56
