### ISSUE TITLE
[SUGGESTION]8ball

### ISSUE THREAD

**Issue by Gamer086** [codeman1o1/TIJK-Bot#94]
Put the 8ball commands of dank memer in tijk bot

**Comment by codeman1o1** [comment]
What responses do you want?

**Comment by Gamer086** [comment]
I dont know, funny answers

**Comment by codeman1o1** [comment]
You can add a answer in [8ball_responses.json](https://github.com/codeman1o1/TIJK-Bot/blob/codeman1o1/issue94/8ball_responses.json) by adding a item to the list by following these steps:
1. Add a comma to the last item
2. Press enter for a new line
3. If there is no indentation, put 4 spaces or a tab
4. Put your new answer in quotation marks. E.g. "my new answer"
It will look something like thislike this:
```json
{
  "responses": [
    "Yes",
    "No",
    "Maybe",
    "I am not sure",
    "I am not sure about that",
    "I do not understand",
    "What will you do when I don't answer?",
    "my new answer"
  ]
}
```

**Comment by codeman1o1** [comment]
Or you can just let me know what extra answers you want
