### ISSUE TITLE
admin change Tijkbot status

### ISSUE THREAD

**Issue by Timmie644** [codeman1o1/TIJK-Bot#97]
### Describe your fix/feature

add a .status command so admins can change the status of tijkbot

**Comment by codeman1o1** [comment]
Do you mean the Online/Away/Busy/Offline status?

**Comment by Timmie644** [comment]
no the Watching/Playing ... status

**Comment by codeman1o1** [comment]
Why do you want that?

**Comment by Timmie644** [comment]
because it is fun
